{"trial_id": "0181", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "sigmoid", "linear"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_5", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_6", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_7", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_8", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_9", "default": null, "conditions": [], "min_value": 1, "max_value": 80, "step": 2, "sampling": "linear"}}], "values": {"activation": "linear", "first_units": 13, "num_layers": 1, "units_0": 31, "units_1": 43, "units_2": 13, "units_3": 21, "units_4": 9, "units_5": 21, "units_6": 39, "units_7": 5, "units_8": 25, "units_9": 29, "tuner/epochs": 12, "tuner/initial_epoch": 4, "tuner/bracket": 3, "tuner/round": 1, "tuner/trial_id": "0170"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 438, in _build_hypermodel\n    model.load_weights(self._get_checkpoint_fname(trial_id))\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\neilg\\anaconda3\\envs\\dev\\lib\\site-packages\\tensorflow\\python\\training\\saving\\saveable_object_util.py\", line 135, in restore\n    raise ValueError(\nValueError: Received incompatible tensor with shape (116, 13) when attempting to restore variable with shape (107, 13) and name layer_with_weights-0/kernel/.ATTRIBUTES/VARIABLE_VALUE.\n"}